name: Docker Build

on:
  push:
    branches:
      - master

jobs:
  build-overture:
    name: Build Overture
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Github Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Tencent Docker Login
        uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_USER }}
          password: ${{ secrets.TENCENT_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/overture/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: |
            ghcr.io/apocalypsor/overture:latest
            ccr.ccs.tencentyun.com/dovlov/overture:latest

  build-smartdns:
    name: Build SmartDNS
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/smartdns/Dockerfile
          push: true
          tags: ghcr.io/apocalypsor/overture:upstream
